version: '3.9'

services:
  nats:
    image: nats:2.9-alpine
    container_name: nats_server
    ports:
      - "4222:4222"
      - "8222:8222"

  ehr_database:
    image: postgres:16.2
    container_name: ehr_database
    environment:
      POSTGRES_USER: ehruser
      POSTGRES_PASSWORD: ehremapta
      POSTGRES_DB: ehrdb
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3-management
    container_name: rabbitmq
    ports:
      - '5672:5672' # Puerto para las conexiones AMQP
      - '15672:15672' # Puerto para el dashboard de RabbitMQ
    environment:
      RABBITMQ_DEFAULT_USER: guest
      RABBITMQ_DEFAULT_PASS: guest

volumes:
  postgres_data:
