version: '3.9'

services:
  nats:
    image: nats:2.9-alpine
    container_name: nats_server
    ports:
      - "4222:4222"
      - "8222:8222"

  postgres:
    image: postgres:15-alpine
    container_name: ehr_postgres
    environment:
      POSTGRES_USER: ehr_user
      POSTGRES_PASSWORD: ehr_emapta
      POSTGRES_DB: ehr_db
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
